SFSettings | Add Agency Events menu item
Smartforce-Technologies-Inc/ui-smartforce-settings pull request #14
Opened 2023-11-10 18:38 UTC by Yopo-Nicolas

2023-11-10 18:53 UTC, martinweingart requested changes

2023-11-10 18:53 UTC, martinweingart commented on src/Context/AgencyEvents.tsx
There's no need for a context for now

2023-11-10 18:53 UTC, martinweingart commented on src/Context/index.ts
> +export * from './AgencyEvents';
Remove

2023-11-10 18:53 UTC, martinweingart commented on src/SFSettings.tsx
> +  if (!isRoleOfficer(user?.role.id) && useSubscription('shift')) {
Bad use of hook. Change useSubscription for getAppSubscription.

Check if the shifts subscription is used in another place and if so, assign it to a variable

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  const { events } = React.useContext(AgencyEventsContext);
Don't use context. Fech the events in a useEffect

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  };
This function can be defined outside the render function

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +            onCreate={onFinish}
`onCreate` should open the creation modal, not finishing a creation

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEventsList/AgencyEventsList.tsx
> +  onView: (event: AgencyEvent) => void;
Why this event?

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  };
What it will do?

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +                onView={onView}
Why this event?

2023-11-10 18:53 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEventsList/AgencyEventsListItem/AgencyEventsListItem.tsx
> +  onClick: () => void;
Why this event?

2023-11-10 19:15 UTC, Yopo-Nicolas commented on src/Context/AgencyEvents.tsx
Removed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Context/index.ts
> +export * from './AgencyEvents';
Removed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/SFSettings.tsx
> +  if (!isRoleOfficer(user?.role.id) && useSubscription('shift')) {
Done, changed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  const { events } = React.useContext(AgencyEventsContext);
Done

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  };
Moved

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +            onCreate={onFinish}
Changed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEventsList/AgencyEventsList.tsx
> +  onView: (event: AgencyEvent) => void;
Removed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +  };
Removed

2023-11-10 19:16 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +                onView={onView}
Removed

2023-11-10 19:17 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEventsList/AgencyEventsListItem/AgencyEventsListItem.tsx
> +  onClick: () => void;
Removed

2023-11-13 10:15 UTC, martinweingart requested changes

2023-11-13 10:15 UTC, martinweingart commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +            onCreate={onFinish}
I can't see the change

2023-11-13 11:27 UTC, Yopo-Nicolas commented on src/Views/AgencyEvents/AgencyEvents.tsx
> +            onCreate={onFinish}
Added missing change

2023-11-13 11:33 UTC, martinweingart approved these changes
LGTM

2023-11-13 11:33 UTC, merged