Feature shift history modal
Smartforce-Technologies-Inc/ui-smartforce-settings pull request #90
Opened 2024-01-08 18:01 UTC by Yopo-Nicolas

2024-01-08 18:16 UTC, martinweingart requested changes

2024-01-08 18:16 UTC, martinweingart commented on src/Helpers/format.ts
> +    if (!isLast && recurrence.days.length - 2 !== index) msg += ', ';
Why this?

2024-01-08 18:16 UTC, martinweingart commented on src/Services/ShiftsService.ts
> +  shift: ShiftHistoryChange
An edit shift request it's not the same as an shift history entry

2024-01-08 18:16 UTC, martinweingart commented on src/Views/AgencyShifts/AgencyShifts.tsx
> +      const shiftResponse = await getShift(apiBaseUrl, shiftId);
It's this needed? The shift information should be present in the clickable item

2024-01-08 18:16 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +function getShiftHistoryChanges(
Why `getShiftHistoryChanges`? This should be something like `getEditedShift`

2024-01-08 18:16 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +    start: shift.start.date?.isSame(value.start.date)
Is this working good? What happens if the day it's the same but not the time?

2024-01-08 18:16 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +
This function (`getShiftHistoryChanges`) is too big, modularize it

2024-01-08 18:16 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
>  const getHistoryItemValue = (
This function is too big, modularize it

2024-01-09 13:31 UTC, Yopo-Nicolas commented on src/Helpers/format.ts
> +    if (!isLast && recurrence.days.length - 2 !== index) msg += ', ';
This is added in order to eliminate the last comma separator before the "and" last value

2024-01-09 13:31 UTC, Yopo-Nicolas commented on src/Services/ShiftsService.ts
> +  shift: ShiftHistoryChange
Changed model name in order to be more descriptive

2024-01-09 13:32 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/AgencyShifts.tsx
> +      const shiftResponse = await getShift(apiBaseUrl, shiftId);
This is needed because the item passed on in the clickable item doesn't have all the information needed in the component.

2024-01-09 13:33 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +function getShiftHistoryChanges(
Changed name of the function

2024-01-09 13:35 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +    start: shift.start.date?.isSame(value.start.date)
Yes this works good because isSame function checks for strict equality in moment Date value

2024-01-09 13:35 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +
Done

2024-01-09 13:35 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
>  const getHistoryItemValue = (
Done

2024-01-09 13:43 UTC, martinweingart requested changes

2024-01-09 13:43 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftFormModal/ShiftFormModal.tsx
> +
Much better!

2024-01-09 13:43 UTC, martinweingart commented on src/Models/Shifts.ts
> +  changes: ShiftEditRequest;
`ShiftHistoryChange` was ok here, maybe to improve readability you could just define another interface like
`type ShiftHistoryChange = ShiftEditRequest` and use `ShiftHistoryChange`here

2024-01-09 13:43 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
> +  historyChanges: ShiftEditRequest,
Change to `ShiftHistoryChange`

2024-01-09 13:43 UTC, martinweingart commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
> +  const historyChanges: ShiftEditRequest = history.changes;
Use of `ShiftHistoryChange` interface was fine here

2024-01-09 16:44 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
> +  historyChanges: ShiftEditRequest,
Done

2024-01-09 16:44 UTC, Yopo-Nicolas commented on src/Views/AgencyShifts/ShiftHistoryModal/ShiftHistoryModal.tsx
> +  const historyChanges: ShiftEditRequest = history.changes;
Done

2024-01-09 17:08 UTC, martinweingart requested changes

2024-01-09 17:08 UTC, martinweingart commented on src/Helpers/format.ts
> +      msg += ` and `;
Check this space

2024-01-09 21:40 UTC, martinweingart approved these changes

2024-01-09 22:18 UTC, merged